# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output out
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'
